[package]
name = "test_helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
rsnano_core = { path = "../../core" }
rsnano_ledger = { path = "../../ledger" }
rsnano_network = { path = "../../network" }
rsnano_node = { path = "../../node", features = ["output_tracking"] }
rsnano_nullable_tcp = { path = "../../nullables/tcp" }
rsnano_rpc_client = { path = "../../rpc_client" }
rsnano_rpc_server = { path = "../../rpc_server" }
rsnano_websocket_server = { path = "../../websocket_server" }
mock_instant = "0"
tracing-subscriber = { version = "0", features = ["env-filter"] }
axum = "0"
tracing-test = "0"
tokio = { version = "1" }
anyhow = "1"
tempfile = "3.13.0"