[package]
name = "rsnano_node"
version = "0.1.0"
authors = ["Gustav Schauwecker <service@simpago.com>"]
edition = "2021"

[features]
output_tracking = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
mock_instant = "0"
tracing-test = "0"
test_helpers = { path = "../tools/test_helpers" }
tempfile = "3.13.0"

[dependencies]
rsnano_core = { path = "../core" }
rsnano_messages = { path = "../messages" }
rsnano_network = { path = "../network" }
rsnano_store_lmdb = { path = "../store_lmdb" }
rsnano_output_tracker = { path = "../nullables/output_tracker" }
rsnano_nullable_fs = { path = "../nullables/fs" }
rsnano_nullable_tcp = { path = "../nullables/tcp" }
rsnano_nullable_lmdb = { path = "../nullables/lmdb" }
rsnano_nullable_http_client = { path = "../nullables/http_client" }
rsnano_nullable_clock = { path = "../nullables/clock" }
rsnano_ledger = { path = "../ledger" }
rsnano_websocket_messages = { path = "../websocket_messages" }
anyhow = "1"
bitvec = "1"
blake2 = "0"
bounded-vec-deque = "0"
chrono = "0"
dirs = "5"
num = "0"
num-derive = "0"
num-traits = "0"
once_cell = "1"
rand = { version = "0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_derive = "1"
siphasher = "1"
static_assertions = "1"
toml_edit = "0"
uuid = { version = "1", features = ["v4"] }
scoped_threadpool = "0.1.*"
backtrace = "0"
serde_variant = "0"
primitive-types = "0"
threadpool = "1"
timer = "0"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "time",
    "macros",
    "sync",
] }
async-trait = "0"
tracing = "0"
ordered-float = "4"
tokio-tungstenite = "0"
futures-util = { version = "0", features = ["sink"] }
tokio-util = "0"
toml = "0"
strum = "0"
strum_macros = "0"
